FROM python:3.11-slim

ENV POETRY_VERSION=1.7.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN apt-get update && apt-get install --no-install-recommends -y curl make \
    && curl -sSL https://install.python-poetry.org | python

WORKDIR /app

COPY backend backend
COPY migrations migrations
COPY pyproject.toml \
     Makefile \
     .

RUN make install
ENTRYPOINT ["make", "run-server"]