[tool.poetry]
name = "inno-trackify"
version = "0.1.0"
description = ""
authors = ["Arseniy <arseniy_zd@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.68.0"
pydantic = "^1.9.0"
uvicorn = "^0.15.0"
sqlalchemy = "^1.4.31"
streamlit = "^1.6.0"
flake8 = "^7.0.0"
black = "^24.3.0"
genbadge = "^1.1.1"
flake8-html = "^0.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"