name: lint

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.19.2